services:
  - type: web
    name: whisper-transcriber
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install torch torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 120 app:app
    envVars:
      - key: FERNET_KEY
        value: ymF95L7Pv82R7yzvWyXdCmwnoIDfhs8shfUWfJF1OUQ=
